services:
  bot:
    build: .
    container_name: rasp_bot
    env_file: .env
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/database.sqlite
    restart: unless-stopped
    tty: true

